### ISSUE TITLE
[FEATURE] Implement a set of extract_* functions to provide an alternative way to extracting tables

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTDataOps/REDCapTidieR#15]
# Feature Request Description
The `bind_tables()` function provides an easy way to make all or a subset of tables derived from a REDCap project in the analyst's environment. However, some may feel like this function has spooky side effects and would like more control over the objects in the environment. I propose a series of helper functions inspired by `tidymodels` that allow extracting one or multiple tables.

# Proposed Solution

Implement two functions, `extract_table()` and `extract_tables()` that allow extracting specific tables from a REDCapTidieR supertibble (good branding?), where:

`extract_table(data, tbl)` takes a supertibble and returns the extracted tibble, and
`extract_tables(data, tbls)` takes a supertibble and returns a _named list_ of the extracted tibbles. 

A really cool feature would be if both functions could support [tidy-select semantics](https://dplyr.tidyverse.org/articles/programming.html) for the `tbl`/`tbls` argument, i.e. allow helpers such as `starts_with()` or `everything()`. This may be a bit tricky to implement because tidy-select operates on columns and the supertibble doesn't organize its content in columns, but this is a solvable problem with a `pivot_wider` transformation.

`extract_table()` should throw an error if more than one table is matched by the `tbl` argument. I think a great way to  implement `extract_table()` would be by calling `extract_tables()`, counting the number of elements in the list, throw an error if it's not exactly one, and then unlist that element.

```r
demographics <- supertibble %>% extract_table("demographics")
```

```r
redcap_data_all <- supertibble %>% extract_tables(everything())
```

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [X] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
@skadauke can you explain a bit more how you envision `extract_tables(.data, tbls = starts_with())` working (or the other tidyselect functions)? I read through the documentation but can't think of a way to get past `Error: ____ must be used within a *selecting* function`.

**Comment by rsh52** [comment]
> @skadauke can you explain a bit more how you envision `extract_tables(.data, tbls = starts_with())` working (or the other tidyselect functions)? I read through the documentation but can't think of a way to get past `Error: ____ must be used within a *selecting* function`.

For now I have a function achieving the behavior we want, `pivot_wider` was good for selecting on columns but was causing me a headache when converting it back to a named list. Here is a simple function using primarily base R, tested on the Classic/Longitudinal and Prodigy databases:

```r
extract_tables <- function(.data,
                           tbls){
  # Check tbls is valid ----
  assert_vector(tbls)

  if (any(!tbls %in% .data$redcap_form_name)){
    stop("tbls not detected in redcap_form_name: ",
         paste(tbls[!tbls %in% .data$redcap_form_name], collapse = ", ")
    )
  }

  # Extract specified table ----
  # Remove structure col
  out <- .data %>% select(-structure)
  # Convert list elements to named list elements using redcap_form_name
  names(out$redcap_data) <- out$redcap_form_name
  # Subset for specified list elements from tbls argument
  out <- out[out$redcap_form_name %in% tbls,]
  # Output the named list
  as.list(out$redcap_data)
}
```

**Comment by rsh52** [comment]
I believe I have this ready to go, currently is being held up by #26 merge (test suite appropriately breaks without proper API privilege handling). Was able to get it to work succinctly using [this vignette](https://cran.r-project.org/web/packages/tidyselect/vignettes/tidyselect.html). Function below:

```r
extract_tables <- function(.data,
                           tbls){

  # Extract specified table ----
  # Pass tbls as an expression for enquosure
  tbls <- rlang::enquo(tbls)

  out <- .data %>%
    select(-.data$structure) %>%
    pivot_wider(names_from = .data$redcap_form_name,
                values_from = .data$redcap_data)

  out <- out[tidyselect::eval_select(tbls, data = out)]

  out %>%
    map(.f = ~pluck(.)[[1]])
}
```

I'll be on the lookout for merges/feedback then can submit this one.
