### ISSUE TITLE
[FEATURE] Augment the supertibble with metadata 

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTDataOps/REDCapTidieR#16]
# Feature Request Description

The supertibble should make it easy for the analyst to discover table-specific metadata. 

# Proposed Solution

Add the following columns to the supertibble returned by `read_redcap_tidy()`:

- `redcap_form_label`: this should be the instrument label returned by `redcap_instruments` 
- `redcap_metadata`: This should be a list column containing data from `db_metadata` specific to the form (i.e. filtered on `form_name`). This will include non-data fields, which I think is OK. I suggest the following modifications from the raw REDCapR output: (1) remove `form_name` as it's redundant; (2) Turn `select_choices_or_calculations` into a list column with tibbles generated by `parse_labels`; (3) Add a list column `events` that contains a tibble of events which which the instrument is associated - skip if not longitudinal. If there are arms in the project, this tibble should have a column "arm" to indicate arms. (4) Reorder columns so the most useful ones are on the left: `field_name`, `field_label`, `field_type` then `everything()` else
- `rows` showing the number of rows of the tibble
- `columns` showing the number of cols of the tibble
- `NA` percentage
- object size

We might want to add more informational columns. For inspiration, see here: https://cghlewis.github.io/codebook-pkg-comparison/
Note, see: https://github.com/skadauke/dataMeta

## Potential Related Enhancement

Use the [`labelled`](https://larmarange.github.io/labelled/) package to add labels from the metadata to fields in the super-tibble as suggest on the CHOP R User Group slack

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by ezraporter** [comment]
I've implemented the basic functionality + tests [here](https://github.com/CHOP-CGTDataOps/REDCapTidieR/tree/add-metadata). Two things:

1. I'm waiting on adding the `events` column until #56 is merged. The refactor of `link_arms()` is just involved enough that it doesn't make sense to recreate it independently on this branch. Merging that and rebasing this branch will be much cleaner.

2. In thinking about some of the bonus elements like number of rows, number of columns, NA%, object size I wonder if we should relegate those things to a `summary()` method. The functionality would be:

```r
redcap_data <- read_redcap_tidy(uri, token)

summary(redcap_data)

#> form  field nrow ncol na_percent ...
#> abc   f1    10   2    0
#> abc   f2    10   2   .1
#> xyz   f1    20   5   .15
#> ...
```
We'd need to create a `supertibble` class and a `summary.supertibble()` method so it would take a bit more infrastructure but not much.
