### ISSUE TITLE
[FEATURE] Make checkbox-multi column names less ugly

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTDataOps/REDCapTidieR#19]
# Feature Request Description

It would be nice if the columns from `checkbox-multi` fields didn't have names with three consecutive underscores in them. 

# Proposed Solution

As part of the "aesthetic cleanup" let's rename any checkbox-multi columns so that they have a single underscore. I'm not sure what the best way is here. The logic probably shouldn't simply rely on looking for three underscores and instead depend on positive identification of checkbox-multi kinds of columns. I think it might be best to implement this inside of `update_field_names()`?

## Additional Context

You'll have to change [tests/testthat/test-clean_redcap.R](https://github.com/CHOP-CGTDataOps/REDCapTidieR/blob/54eaeb5a0a426af9dd99f66cae19343f1f14dcfb/tests/testthat/test-clean_redcap.R).

Let's target v0.1 because this will be a breaking change.

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [X] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
In case this needs to be revisited in the future, this issue was marked "closed" because the default REDCap behavior is to assign `*___*` to the variable names of checkboxes. The concern was users would potentially turn to the codebook to look for the variables and find differences.
