### ISSUE TITLE
[BUG] redcap_ready_tidy fails on checkbox field with negative value

### ISSUE THREAD

**Issue by pwildenhain** [CHOP-CGTDataOps/REDCapTidieR#31]
# Expected Behavior
`redcap_read_tidy` should be able to handle all types of fields

# Current Behavior
I have several checkbox fields in my project where the value `'Unknown'` is coded as `-99`. In the data export REDCap converts the minus sign `-` into an underscore `_`. For example, if the patients identifies as white then `race___4` will be `1` but if they refuse to supply their race then `race____99` will be `1` -- notice the four underscores instead of the 3 underscores for the `'Unknown'` option

It seems like this break assumptions that `redcap_ready_tidy` makes, since I get this error message:

```r
> read_redcap_tidy(uri, token)
```
```
Error in `mutate()`:
! Problem while computing `..1 = across(.cols =
  all_of(logical_cols), as.logical)`.
Caused by error in `across()`:
! Can't subset columns that don't exist.
x Column `race___-99` doesn't exist.
```

After searching through the source code I suspect the underlying issue is here:

https://github.com/CHOP-CGTDataOps/REDCapTidieR/blob/1fd9b7763fbd85e59be7a0a5659092c8ab1d7dfb/R/utils.R#L133-L142

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [ ] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
@skadauke 

Paul and I met and tested creating variables with different prefix characters for raw checkbox values (`-99`, `---99`, `-_9-9`, `?99`, `*99`) and found that REDCap's default export behavior is to convert all `-`s to `_`s.

- `checkbox___-99` -> `checkbox____99`
- `checkbox___-9-9` -> `checkbox____9_9`

So luckily this does not appear to influence any other characters. If a different prefix character gets supplied to a raw value (like `?99`) REDCap's front end auto assigns a number and comma to the raw value and groups the remainder to the label value:

![image](https://user-images.githubusercontent.com/38384694/188192499-4a6cbd97-1e29-4c15-bc5d-8bd7ce348274.png)

I think this should be a simple fix with `str_replace` to convert all raw `-`s to `_`s.
