### ISSUE TITLE
[FEATURE] REDCapTidieR Option to Only Load Specific Forms

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#36]
# Feature Request Description

For large databases, it is not desirable to extract everything into a `REDCapTidieR` output (the current default behavior) from `REDCapR::redcap_read_oneshot`. Users should have the option to specify forms for extraction to minimize load times and memory use.

# Proposed Solution

There should be an option in `read_redcap_tidy` where users specify forms. This should trickle to `redcap_read_oneshot` for the extraction.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by ezraporter** [comment]
An initial approach is to pass the `forms` argument to `read_redcap_oneshot()` and `redcap_metadata_read()` in `read_redcap_tidy()`

https://github.com/CHOP-CGTDataOps/REDCapTidieR/blob/5d25913e3ad21733322eebef68eb8600d4bf488e/R/read_redcap_tidy.R#L57-L67

`redcap_metadata_read()` doesn't seem to be handling the `forms` argument correctly. Currently investigating the issue.

**Comment by ezraporter** [comment]
> redcap_metadata_read() doesn't seem to be handling the forms argument correctly.

This appears to be a genuine issue with `REDCapR`. Possibly related to the format that [Export Metadata](https://redcap.chop.edu/api/help/?content=exp_metadata) method expects for its `forms` parameter. (`REDCapR` passes a comma-separated list as a string which may not be acceptable.)

```r
# uri and token from ?redcap_metadata_read examples
uri   <- "https://bbmc.ouhsc.edu/redcap/api/"
token <- "9A81268476645C4E5F03428B8AC3AA7B"
resp <- REDCapR::redcap_metadata_read(redcap_uri=uri,
                                      token=token,
                                      # name of a single form in the example data
                                      forms = "health")$data

all(resp$form_name == "health")
#> FALSE
```

Given the issues around backwards compatibility if we did get a fix, I think filtering right after the call to `redcap_metadata_read()` is the best solution but open to discussion.

We should probably alert Will as well. Is an issue in the `REDCapR` repo the best bet or email?

cc: @skadauke
