### ISSUE TITLE
[BUG] REDCapTidieR doesn't return survey timestamp fields

### ISSUE THREAD

**Issue by tschuler** [CHOP-CGTDataOps/REDCapTidieR#55]
Amazing, elegant work 💪  I have been battling with REDCap's 'block matrix' data format written my own much less elegant conversion scripts. Thanks so much for sharing with the community.

# Enhancment Idea
Unless have overlooked something, currently the CRAN version of REDCapTidieR doesn't expose the survey timestamp field.

# Proposed Solution
Expose the 'survey_timestamp' field for all instruments of type survey similar to 'form_status_complete'.

**Comment by skadauke** [comment]
Thanks @tschuler for the kind words and for the bug report! @ezraporter and @rsh52, I don't think we have test coverage for surveys yet. Let's create an issue to look into the missing survey timestamp field as well as any other fields that may be survey specific that we're missing currently.

**Comment by tschuler** [comment]
> Thanks @tschuler for the kind words and for the bug report! @ezraporter and @rsh52, I don't think we have test coverage for surveys yet. Let's create an issue to look into the missing survey timestamp field as well as any other fields that may be survey specific that we're missing currently.
> 
> I'm also relabeling this feature request as a bug to bump its importance.

Hi @skadauke, @ezraporter and @rsh52,

Thanks so much for considering and bumping. As far as I know the submission timestamp and the completion status are the only easily accessible survey metadata. 

The only other thing that would be super useful but is not directly supported by the REDCap API and therefore probably out of scope for REDCapTidieR is: a way to distinguish 'never invited' surveys from 'non-responded' surveys (both appear as not completed) but when trying to figure out compliance/adherance obviously makes a huge difference. 
I have been manually downloading the survey invitation log and written clumpsy scripts to figure this out...However there is a way to pull the survey invitation log via REDCapR (see https://github.com/OuhscBbmc/REDCapR/issues/230). 
Maybe you or other talented people on your team want to tackle the challenge to solve this generically... But obviously could be way out of scope...

Cheers, Thilo

**Comment by rsh52** [comment]
@tschuler We have implemented `*_timestamp` and `redcap_survey_identifier` as outputs in the most recent development version, aiming to have it included in our 0.2 release soon.
