### ISSUE TITLE
[BUG] REDCapTidieR Does not capture checkboxes

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#6]
# Expected Behavior
Checkbox data types should be accurately displayed in the `tibble` outputs. For an example `variable` with 3 possible selection options, the following output can be expected: 

- `variable__1`
- `variable__2`
- `variable__3`

# Current Behavior
`REDCapTidieR` doesn't accurately capture checkbox data types. 

This is likely because the `field_name` in the metadata is assigned the REDCap variable name (ex: `infseq_confirmation`) while the named output has a number attached to each possible sub-variable (ex: `infseq_confirmation__1`).

## How to Reproduce the Bug:
Check the output for a missing `infseq_confirmation` in the `infusion_sequence` datatable for Prodigy, or in any other checkbox variable like Cohort selection.

**Screenshots**:
Metadata Output:
![image](https://user-images.githubusercontent.com/38384694/182232227-a964e5cf-46a5-40cb-94ea-700adb2b777b.png)

Data Output:
![image](https://user-images.githubusercontent.com/38384694/182232314-33ccc84c-302b-4221-9275-a198c708ddd7.png)

## Failure Logs

If applicable, submit any failure logs or error messages here.

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by rsh52** [comment]
Will have to reassess how we use `my_fields` with `db_data`, issue stems from :

`my_fields <- intersect(my_fields, names(db_data_long))`

**Comment by skadauke** [comment]
So basically the `intersect` relied on the assumption that we can capture every column we want by looking at the metadata which associated each instrument with a set of columns, but we forgot that the columns for multi choice checkboxes get expanded to this ugly `*__n` format?

**Comment by skadauke** [comment]
One more thought - we should really have a test that all different field types are represented in the table as expected. So I would suggest adding one of each field type to one of the forms in the test database and then testing that all columnsmake it into the tibble as expected.

**Comment by rsh52** [comment]
Correct, I was looking into if we can somehow use a `contains()` type function in combination with `intersect` or do a `grepl`/SQL-esque `like` operation. If you know any good solutions for this off the top of your head I'm all ears!

We also do not capture any `*_complete` data (i.e. when a form is Red/Yellow/Green or "Complete"/"Incomplete"/"Unverified") because this doesn't appear in the `metadata` object. I don't think we need it now but it can be useful if you need to check for form completeness or reference it as an indicator for for whether to use a record.

**Comment by skadauke** [comment]
Great point about `*_complete` - we should add this.

Maybe we're going about the `intersect` thing all wrong. Perhaps the best way is to implement logic dependent on the specific field type - include, exclude, transform in a specific way.

**Comment by rsh52** [comment]
> One more thought - we should really have a test that all possible REDCap field types are represented in the tibble as expected. So I would suggest adding one field of each type to one of the forms in the test database and then writing a test that all columns make it into the tibble as expected.

Agree, would be good to have the option to keep/remove metadata of `field_type` "descriptive" but I have to check on whether the current logic would prevent that. Still have to start making the superheros db, hopefully will get to that today.

**Comment by rsh52** [comment]
Putting a stream of consciousness here:

### REDCap Field Types
I think one thing we'll want to do is allow for filtering by `field_type`, so for our records I made a temporary instrument with every possible REDCap input so we have a record of all the different `field_type`s which we probably don't need hard coded but will be good for the reference documentation (`?help`):

![image](https://user-images.githubusercontent.com/38384694/182382184-dec1012e-3ad9-490a-a0ee-3725d96fe4cd.png)

`field_type`s are:
"text", "notes", "calc", "dropdown", "radio", "checkbox", "yesno", "truefalse", "file", "slider", "descriptive"

### REDCap `*_complete`

I think this can be a single T/F input since there's no reference in the metadata output and no way in `REDCapR::redcap_metadata_read` to output it. Something akin to `completion = TRUE/FALSE`.

### REDCap checkboxes

Still working on this one... checkboxes are annoying.
