### ISSUE TITLE
[FEATURE] Improve `field_label` metadata for checkbox fields

### ISSUE THREAD

**Issue by ezraporter** [CHOP-CGTDataOps/REDCapTidieR#70]
# Feature Request Description
Currently when checkbox fields are expanded in the metadata to have one row per checkbox option the field label from the checkbox field is carried over to all new rows. Field labels for each new row should be updated to include the option label in addition to the field label.

This addresses the conversation in https://github.com/CHOP-CGTDataOps/REDCapTidieR/pull/65#issuecomment-1306177174 

# Proposed Solution
Update `update_field_names()` to append field labels with option labels. See https://github.com/CHOP-CGTDataOps/REDCapTidieR/pull/65#issuecomment-1306177174 for example output.

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment]
This logic will need to be able to deal with embedded fields that are part of the choice label. E.g.:

field_name | field_label | select_choices_or_calculations
-- | -- | --
crs_anti_tcell_therapy_types | Anti-T Cell therapy given: | cyclophosphamide, Cyclophosphamide \| atg, ATG \| other, Other {crs_anti_tcell_therapy_types_specify}

The field label should be: 

`Anti-T Cell therapy given: Other` 

and not 

`Anti-T Cell therapy given: Other {crs_anti_tcell_therapy_types_specify}`. 

There may be variable amount of whitespace before the opening curly bracket. I don't know if there will ever be more than one embedded field but you never know. I'm thinking a regex that removes everything bounded by curlies and then strips whitespace from the right end of the string would do the trick.
