### ISSUE TITLE
[BUG] extract_tables no longer works with new field additions

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#75]
# Expected Behavior
The `extract_table/s` functions should return the expected tables from a `read_redcap_tidy` call.

# Current Behavior
`NULL` values are returned instead of `tibble`s when using `extract` functions with table specs. 

This was not being picked up by our test suite because non-API tests require manual updates of the .RDS files they reference. We may want to think of a better way to update internal/non-API tests or ensure updating the files is a part of our checklist (the current file for doing so is under `/inst/create_test_data.R`).

## How to Reproduce the Bug:
Take a current `read_redcap_tidy` output and supply a specification to `extract_tables`.

## Proposed Solution:
The culprit here is how `extract_tables` shaves off supertibble columns that aren't necessary:
https://github.com/CHOP-CGTDataOps/REDCapTidieR/blob/3944c913990bcd8f9f314a591357c20e01d2adc4/R/extract_table.R#L98-L106

In brief testing I believe all we have to do here is change `select(-"structure)` to `select("redcap_form_name", "redcap_data")`. I think when I originally wrote this it was without the idea that we'd be adding onto the supertibble, but now it makes sense to specifically call out only the columns we need to shore up new additions.

Would welcome thoughts on how to avoid silent test failures like this in the future.

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by ezraporter** [comment]
That solution sounds right.

Would adding something to our PR checklist be enough? I actually didn't know I was supposed to rerun that script 😅

Another option is having some integration tests in addition to unit tests that do things like check that the output of `read_redcap_tidy()` works with `extract_tables()`, `make_labelled()`, etc. We could even just run those in our CI and skip on CRAN.

**Comment by rsh52** [comment]
I agree, I think the best bet here is to enforce the .RDS files update via non-CRAN execution. 

Another option is to reshape the tests that use those files to instead use the outputs of the supertibbles from the mocks. I don't entirely like this method though because it's kind of testing `read_redcap_tidy` as well and that's not the purpose of these tests.

For now I can fix this bug as proposed and open a new issue for test updates. Thoughts?

**Comment by rsh52** [comment]
Will be addressing this bug in an upcoming PR and opening a new feature/bug Issue for addressing our test suite
