### ISSUE TITLE
Convert Text Box data to the appropriate data type based on Validation type

### ISSUE THREAD

**Issue by skadauke** [CHOP-CGTDataOps/REDCapTidieR#9]
# Feature Request Description

Text Box data entry fields are special because they can contain many different types of data in addition to text. These data types should be converted to the appropriate data type in R (maybe that's already happening? But I wanted to jot this down while I was thinking about it). See screenshot for the Validation types available in CHOP's REDCap:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/10904538/182480352-009e46e6-eb00-455c-aa5d-a3cf434ee62a.png">

# Proposed Solution

I would hope that the validation type is captured in the metadata tibble. I think, here's how things should map--

| Validation type  |  R data type |
| ------------- | ------------- |
| Date (all variants)  | `Date`  |
| Datetime (all variants)  | `POSIXct`  |
| Integer | `numeric` |
| Number (all variants) | `numeric` |

`lubridate` functions will be helpful in converting the various date and datetime formats. 

I don't think there is a good representation of Time (without date) so would leave that as a `character`.

# Tests

I think we'll need another instrument in the `nonrepeat` instrument with all of these and write a test to make sure we get the expected results.

### Checklist

- [X] The issue is atomic
- [X] The issue description is documented
- [X] The issue title describes the problem succinctly
- [X] Developers are assigned to the issue
- [X] Labels are assigned to the issue

**Comment by rsh52** [comment]
Sounds good, I think we can also throw in some `assert`s from `checkmate` to ensure data types like date/datetime are handled correctly. Anything you didn't include in the "Proposed Solution" table will likely be `character`. 

Checking the test Prodigy outputs, dates do get converted to one format (in Excel its MDY, in R its YMD). See below for the `infusion` instrument table where `infusion_date` is entered in REDCap as MDY format, but `infusion_dosing_weight_kg_date` is entered as DMY format:

### REDCap Codebook:
![image](https://user-images.githubusercontent.com/38384694/182641018-cf13b006-2a16-4c9e-a09c-0362d497e8fa.png)

### REDCapTidieR Output:

```r
> infusion %>% select(infseq_id, infusion_date, infusion_dosing_weight_kg_date)
# A tibble: 18 × 3
   infseq_id       infusion_date infusion_dosing_weight_kg_date
   <chr>           <date>        <date>                        
 1 19CT023-003.0   NA            NA                            
 2 19CT023-012.0   2020-11-03    2020-08-20                    
 3 19CT023-012.1   2021-02-17    2020-08-20                    
 4 22CT011-001.0   NA            NA                            
 5 22CT011-901.0   2022-02-08    2022-02-08                    
 6 22CT011-902.0   2021-11-08    2021-11-08  
```

**Comment by rsh52** [comment]
I created a test instrument with all the different input validation types for text fields. Here are my findings, hopefully wraps up everything we wanted to know:

- All date time objects get automatically converted to `YYYY-MM-DD HH:MM:SS` and are of class `"POSIXct" "POSIXt" ` ✅ 
- All date objects are of class `Date`
- All time objects (hms, hm, ms) are of class `"hms"      "difftime"` ✅ 
- MRNs, phone numbers, ZIP codes, SSNs are `character` types ✅ 

So I think we're good. We can add some `assert`s if we want but otherwise I think we can rely on REDCap/`REDCapR` to export in the expected formats.

```r
> text_input_validation_types
# A tibble: 3 × 18
  record_id text_dmy   text_dmy_hm         text_dmy_hms        text_mdy   text_mdy_hm         text_mdy_hms        text_ymd  
      <dbl> <date>     <dttm>              <dttm>              <date>     <dttm>              <dttm>              <date>    
1         1 2022-08-03 2022-08-03 15:15:00 2022-08-03 15:15:04 2022-08-03 2022-08-03 15:15:00 2022-08-03 15:15:04 2022-08-03
2         2 NA         NA                  NA                  NA         NA                  NA                  NA        
3         3 NA         NA                  NA                  NA         NA                  NA                  NA        
# … with 10 more variables: text_ymd_hm <dttm>, text_ymd_hms <dttm>, text_mrn <chr>, text_phone <chr>, text_ssn <chr>, text_hms <time>,
#   text_hm <time>, text_ms <time>, text_zip <chr>, form_status_complete <dbl>
# ℹ Use `colnames()` to see all variable names
```

**Comment by skadauke** [comment]
Did we decide that this is resolved because `REDCapR` already handles this correctly?

**Comment by rsh52** [comment]
Yes, at least that's what I found and believe to be true.
